import { InstantItemType, InventoryType, ItemMagicType, PocketItemType } from "./Inventory";
import { LootMap } from "./Loot";

export const lootMap: LootMap = {
    1: [
        {
            name: 'Gloves 20%',
            hitChance: 20,
            price: 5,
            baseValueStep: 1,
            baseValueMax: 25,
            type: InventoryType.gloves,
            baseLevel: 1,
        },
        {
            name: 'Money 10',
            money: 10,
            type: InstantItemType.money,
        },
        {
            name: 'Sword 2',
            dmg: 2,
            price: 2,
            baseValueStep: 1,
            baseValueMax: 4,
            type: InventoryType.weapon,
            baseLevel: 1,
        },
        {
            name: 'Healing 20',
            hp: 20,
            type: InstantItemType.healing,
        },
        {
            name: 'Armor 1%',
            blockPercent: 1,
            price: 3,
            baseValueStep: 1,
            baseValueMax: 5,
            type: InventoryType.armor,
            baseLevel: 1,
        },
        {
            name: 'Money 10',
            money: 10,
            type: InstantItemType.money,
        },
        {
            name: 'Min health potion (+20 HP)',
            hp: 20,
            price: 20,
            type: PocketItemType.healthPotion,
        },
        {
            name: 'Boots 1.1',
            rate: 1.1,
            price: 5,
            baseValueStep: 0.1,
            baseValueMax: 1.5,
            type: InventoryType.boots,
            baseLevel: 1,
        },
        {
            name: 'Experience 10',
            experience: 10,
            type: InstantItemType.experience,
        },
        {
            name: 'Min mana potion (+20 MP)',
            mana: 20,
            price: 20,
            type: PocketItemType.manaPotion,
        },
        {
            name: 'Shield 1%',
            blockChance: 1,
            price: 3,
            baseValueStep: 1,
            baseValueMax: 2,
            type: InventoryType.shield,
            baseLevel: 1,
        },
        {
            name: 'Healing 20',
            hp: 20,
            type: InstantItemType.healing,
        },
        {
            name: 'Experience 10',
            experience: 10,
            type: InstantItemType.experience,
        },
        {
            name: 'Gloves 25%',
            hitChance: 25,
            price: 50,
            baseValueStep: 1,
            baseValueMax: 35,
            type: InventoryType.gloves,
            baseLevel: 2,
        },
        {
            name: 'Money 10',
            money: 10,
            type: InstantItemType.money,
        },
        {
            name: 'Sword 4',
            dmg: 4,
            price: 4,
            baseValueStep: 1,
            baseValueMax: 6,
            type: InventoryType.weapon,
            baseLevel: 2,
        },
        {
            name: 'Healing 20',
            hp: 20,
            type: InstantItemType.healing,
        },
        {
            name: 'Shield 2%',
            blockChance: 2,
            price: 8,
            baseValueStep: 1,
            baseValueMax: 4,
            type: InventoryType.shield,
            baseLevel: 2,
        },
        {
            name: 'Helmet 1',
            blockValue: 1,
            price: 5,
            baseValueStep: 1,
            baseValueMax: 2,
            type: InventoryType.helmet,
            baseLevel: 1,
        },
        {
            name: 'Min mana potion (+20 MP)',
            mana: 20,
            price: 20,
            type: PocketItemType.manaPotion,
        },
        {
            name: 'Experience 10',
            experience: 10,
            type: InstantItemType.experience,
        },
        {
            name: 'Armor 5%',
            blockPercent: 5,
            price: 8,
            baseValueStep: 1,
            baseValueMax: 10,
            type: InventoryType.armor,
            baseLevel: 2,
        },
        {
            name: 'Healing 20',
            hp: 20,
            type: InstantItemType.healing,
        },
        {
            name: 'Sword 6',
            dmg: 6,
            price: 6,
            baseValueStep: 1,
            baseValueMax: 8,
            type: InventoryType.weapon,
            baseLevel: 3,
        },
        {
            name: 'Shield 4%',
            blockChance: 4,
            price: 30,
            baseValueStep: 1,
            baseValueMax: 7,
            type: InventoryType.shield,
            baseLevel: 3,
        },
        {
            name: 'Money 10',
            money: 10,
            type: InstantItemType.money,
        },
        {
            name: 'Experience 10',
            experience: 10,
            type: InstantItemType.experience,
        },
        {
            name: 'Sword 8',
            dmg: 8,
            price: 10,
            baseValueStep: 1,
            baseValueMax: 10,
            type: InventoryType.weapon,
            baseLevel: 4,
        },
        {
            name: 'Armor 10%',
            blockPercent: 10,
            price: 30,
            baseValueStep: 1,
            baseValueMax: 15,
            type: InventoryType.armor,
            baseLevel: 3,
        },
        {
            name: 'Min health potion (+20 HP)',
            hp: 20,
            price: 20,
            type: PocketItemType.healthPotion,
        },
        {
            name: 'Boots 1.5',
            rate: 1.5,
            price: 50,
            baseValueStep: 0.1,
            baseValueMax: 2,
            type: InventoryType.boots,
            baseLevel: 2,
        },
        {
            name: 'Sword 10',
            dmg: 10,
            price: 20,
            baseValueStep: 1,
            baseValueMax: 15,
            type: InventoryType.weapon,
            baseLevel: 5,
        },
        {
            name: 'Money 10',
            money: 10,
            type: InstantItemType.money,
        },
        {
            name: 'Helmet 2',
            blockValue: 2,
            price: 50,
            baseValueStep: 1,
            baseValueMax: 5,
            type: InventoryType.helmet,
            baseLevel: 2,
        },
        {
            name: 'Experience 10',
            experience: 10,
            type: InstantItemType.experience,
        },
        {
            name: 'Healing 20',
            hp: 20,
            type: InstantItemType.healing,
        },
    ],
    2: [
        {
            name: 'Money 50',
            money: 50,
            type: InstantItemType.money,
        },
        {
            name: 'Gloves 35%',
            hitChance: 35,
            price: 500,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.gloves,
            baseLevel: 3,
        },
        {
            name: 'Experience 50',
            experience: 50,
            type: InstantItemType.experience,
        },
        {
            name: 'Tiny health potion (+50 HP)',
            hp: 50,
            price: 50,
            type: PocketItemType.healthPotion,
        },
        {
            name: 'Money 50',
            money: 50,
            type: InstantItemType.money,
        },
        {
            name: 'Armor 10% M',
            blockPercent: 10,
            price: 50,
            baseValueStep: 1,
            baseValueMax: 15,
            type: InventoryType.armor,
            magic: ItemMagicType.magic,
            baseLevel: 3,
        },
        {
            name: 'Weapon 10 M',
            dmg: 10,
            price: 33,
            baseValueStep: 1,
            baseValueMax: 15,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 5,
        },
        {
            name: 'Boots 2',
            rate: 2,
            price: 500,
            baseValueStep: 0.1,
            baseValueMax: 3,
            type: InventoryType.boots,
            baseLevel: 3,
        },
        {
            name: 'Experience 50',
            experience: 50,
            type: InstantItemType.experience,
        },
        {
            name: 'Shield 4% M',
            blockChance: 4,
            price: 50,
            baseValueStep: 1,
            baseValueMax: 7,
            type: InventoryType.shield,
            magic: ItemMagicType.magic,
            baseLevel: 3,
        },
        {
            name: 'Weapon 15',
            dmg: 15,
            price: 40,
            baseValueStep: 1,
            baseValueMax: 20,
            type: InventoryType.weapon,
            baseLevel: 6,
        },
        {
            name: 'Experience 50',
            experience: 50,
            type: InstantItemType.experience,
        },
        {
            name: 'Helmet 2 M',
            blockValue: 2,
            price: 100,
            baseValueStep: 1,
            baseValueMax: 5,
            type: InventoryType.helmet,
            magic: ItemMagicType.magic,
            baseLevel: 2,
        },
        {
            name: 'Healing 50',
            hp: 50,
            type: InstantItemType.healing,
        },
        {
            name: 'Small mana potion (+50 MP)',
            mana: 50,
            price: 50,
            type: PocketItemType.manaPotion,
        },
        {
            name: 'Armor 15%',
            blockPercent: 15,
            price: 80,
            baseValueStep: 1,
            baseValueMax: 20,
            type: InventoryType.armor,
            baseLevel: 4,
        },
        {
            name: 'Money 50',
            money: 50,
            type: InstantItemType.money,
        },
        {
            name: 'Shield 7%',
            blockChance: 7,
            price: 80,
            baseValueStep: 1,
            baseValueMax: 10,
            type: InventoryType.shield,
            baseLevel: 4,
        },
        {
            name: 'Weapon 20',
            dmg: 20,
            price: 60,
            baseValueStep: 1,
            baseValueMax: 25,
            type: InventoryType.weapon,
            baseLevel: 7,
        },
        {
            name: 'Gloves 25% M',
            hitChance: 25,
            price: 100,
            baseValueStep: 1,
            baseValueMax: 35,
            type: InventoryType.gloves,
            magic: ItemMagicType.magic,
            baseLevel: 2,
        },
        {
            name: 'Weapon 15 M',
            dmg: 15,
            price: 53,
            baseValueStep: 1,
            baseValueMax: 20,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 6,
        },
        {
            name: 'Money 50',
            money: 50,
            type: InstantItemType.money,
        },
        {
            name: 'Armor 15% M',
            blockPercent: 15,
            price: 150,
            baseValueStep: 1,
            baseValueMax: 20,
            type: InventoryType.armor,
            magic: ItemMagicType.magic,
            baseLevel: 4,
        },
        {
            name: 'Tiny health potion (+50 HP)',
            hp: 50,
            price: 50,
            type: PocketItemType.healthPotion,
        },
        {
            name: 'Shield 10%',
            blockChance: 10,
            price: 300,
            baseValueStep: 1,
            baseValueMax: 15,
            type: InventoryType.shield,
            baseLevel: 5,
        },
        {
            name: 'Experience 50',
            experience: 50,
            type: InstantItemType.experience,
        },
        {
            name: 'Helmet 5',
            blockValue: 5,
            price: 500,
            baseValueStep: 1,
            baseValueMax: 10,
            type: InventoryType.helmet,
            baseLevel: 3,
        },
        {
            name: 'Weapon 20 M',
            dmg: 20,
            price: 90,
            baseValueStep: 1,
            baseValueMax: 25,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 7,
        },
        {
            name: 'Armor 20%',
            blockPercent: 20,
            price: 300,
            baseValueStep: 1,
            baseValueMax: 30,
            type: InventoryType.armor,
            baseLevel: 5,
        },
        {
            name: 'Small mana potion (+50 MP)',
            mana: 50,
            price: 50,
            type: PocketItemType.manaPotion,
        },
        {
            name: 'Boots 1.5 M',
            rate: 1.5,
            price: 100,
            baseValueStep: 0.1,
            baseValueMax: 2,
            type: InventoryType.boots,
            magic: ItemMagicType.magic,
            baseLevel: 2,
        },
        {
            name: 'Healing 50',
            hp: 50,
            type: InstantItemType.healing,
        },
        {
            name: 'Money 50',
            money: 50,
            type: InstantItemType.money,
        },
        {
            name: 'Shield 7% M',
            blockChance: 7,
            price: 150,
            baseValueStep: 1,
            baseValueMax: 10,
            type: InventoryType.shield,
            magic: ItemMagicType.magic,
            baseLevel: 4,
        },
        {
            name: 'Experience 50',
            experience: 50,
            type: InstantItemType.experience,
        },
        {
            name: 'Weapon 25',
            dmg: 25,
            price: 100,
            baseValueStep: 1,
            baseValueMax: 30,
            type: InventoryType.weapon,
            baseLevel: 8,
        },
    ],
    3: [
        // шкода вогнем 50
        {
            name: 'Minor health potion (+100 HP)',
            hp: 100,
            price: 100,
            type: PocketItemType.healthPotion,
        },
        {
            name: 'Gloves 35% M',
            hitChance: 35,
            price: 1000,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.gloves,
            magic: ItemMagicType.magic,
            baseLevel: 3,
        },
        // рубін
        {
            name: 'Middle mana potion (+100 MP)',
            mana: 100,
            price: 100,
            type: PocketItemType.manaPotion,
        },
        // топаз
        {
            name: 'Armor 20% M',
            blockPercent: 20,
            price: 500,
            baseValueStep: 1,
            baseValueMax: 30,
            type: InventoryType.armor,
            magic: ItemMagicType.magic,
            baseLevel: 5,
        },
        // шкода холодом 50
        {
            name: 'Boots 2 M',
            rate: 2,
            price: 1000,
            baseValueStep: 0.1,
            baseValueMax: 3,
            type: InventoryType.boots,
            magic: ItemMagicType.magic,
            baseLevel: 3,
        },
        {
            name: 'Minor health potion (+100 HP)',
            hp: 100,
            price: 100,
            type: PocketItemType.healthPotion,
        },
        {
            name: 'Weapon 25 M',
            dmg: 25,
            price: 170,
            baseValueStep: 1,
            baseValueMax: 30,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 8,
        },
        // діамант
        {
            name: 'Armor 30%',
            blockPercent: 30,
            price: 800,
            baseValueStep: 1,
            baseValueMax: 40,
            type: InventoryType.armor,
            baseLevel: 6,
        },
        // шкода водою 50
        {
            name: 'Weapon 30',
            dmg: 30,
            price: 200,
            baseValueStep: 2,
            baseValueMax: 40,
            type: InventoryType.weapon,
            baseLevel: 9,
        },
        {
            name: 'Shield 10% M',
            blockChance: 10,
            price: 500,
            baseValueStep: 1,
            baseValueMax: 15,
            type: InventoryType.shield,
            magic: ItemMagicType.magic,
            baseLevel: 5,
        },
        // сапфір
        {
            name: 'Gloves 50%',
            hitChance: 50,
            price:5000,
            baseValueStep: 1,
            baseValueMax: 70,
            type: InventoryType.gloves,
            baseLevel: 4,
        },
        {
            name: 'Weapon 30 M',
            dmg: 330,
            price: 100,
            baseValueStep: 2,
            baseValueMax: 40,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 9,
        },
        {
            name: 'Middle mana potion (+100 MP)',
            mana: 100,
            price: 100,
            type: PocketItemType.manaPotion,
        },
        {
            name: 'Helmet 5 M',
            blockValue: 5,
            price: 1000,
            baseValueStep: 1,
            baseValueMax: 10,
            type: InventoryType.helmet,
            magic: ItemMagicType.magic,
            baseLevel: 3,
        },
        {
            name: 'Shield 15%',
            blockChance: 15,
            price: 800,
            baseValueStep: 1,
            baseValueMax: 20,
            type: InventoryType.shield,
            baseLevel: 6,
        },
        {
            name: 'Minor health potion (+100 HP)',
            hp: 100,
            price: 100,
            type: PocketItemType.healthPotion,
        },
        {
            name: 'Weapon 40',
            dmg: 40,
            price: 400,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.weapon,
            baseLevel: 10,
        },
        {
            name: 'Armor 30% M',
            blockPercent: 30,
            price: 1500,
            baseValueStep: 1,
            baseValueMax: 40,
            type: InventoryType.armor,
            magic: ItemMagicType.magic,
            baseLevel: 6,
        },
        {
            name: 'Weapon 40 M',
            dmg: 40,
            price: 530,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 10,
        },
        // руна1
        {
            name: 'Shield 15% M',
            blockChance: 15,
            price: 1500,
            baseValueStep: 1,
            baseValueMax: 20,
            type: InventoryType.shield,
            magic: ItemMagicType.magic,
            baseLevel: 6,
        },
        {
            name: 'Boots 3',
            rate: 3,
            price: 5000,
            baseValueStep: 0.1,
            baseValueMax: 5,
            type: InventoryType.boots,
            baseLevel: 4,
        },
        {
            name: 'Weapon 50',
            dmg: 50,
            price: 600,
            baseValueStep: 1,
            baseValueMax: 60,
            type: InventoryType.weapon,
            baseLevel: 11,
        },
        {
            name: 'Armor 40%',
            blockPercent: 40,
            price: 3000,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.armor,
            baseLevel: 7,
        },
        {
            name: 'Middle mana potion (+100 MP)',
            mana: 100,
            price: 100,
            type: PocketItemType.manaPotion,
        },
        {
            name: 'Weapon 50 M',
            dmg: 50,
            price: 900,
            baseValueStep: 1,
            baseValueMax: 60,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 11,
        },
        {
            name: 'Shield 20%',
            blockChance: 20,
            price: 3000,
            baseValueStep: 1,
            baseValueMax: 30,
            type: InventoryType.shield,
            baseLevel: 7,
        },
        {
            name: 'Weapon 60',
            dmg: 60,
            price: 1000,
            baseValueStep: 2,
            baseValueMax: 80,
            type: InventoryType.weapon,
            baseLevel: 12,
        },
        {
            name: 'Helmet 10',
            blockValue: 10,
            price: 5000,
            baseValueStep: 1,
            baseValueMax: 20,
            type: InventoryType.helmet,
            baseLevel: 4,
        },
    ],
    4: [
        {
            name: 'Small health potion (+150 HP)',
            hp: 150,
            price: 150,
            type: PocketItemType.healthPotion,
        },
        {
            name: 'Gloves 35% R',
            hitChance: 35,
            price: 2000,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.gloves,
            magic: ItemMagicType.rare,
            baseLevel: 3,
        },
        {
            name: 'Boots 2 R',
            rate: 2,
            price: 2000,
            baseValueStep: 0.1,
            baseValueMax: 3,
            type: InventoryType.boots,
            magic: ItemMagicType.rare,
            baseLevel: 3,
        },
        {
            name: 'Weapon 30 R',
            dmg: 30,
            price: 460,
            baseValueStep: 2,
            baseValueMax: 40,
            type: InventoryType.weapon,
            magic: ItemMagicType.rare,
            baseLevel: 9,
        },
        // баф вогнем 100
        {
            name: 'Armor 20% R',
            blockPercent: 20,
            price: 700,
            baseValueStep: 1,
            baseValueMax: 30,
            type: InventoryType.armor,
            magic: ItemMagicType.rare,
            baseLevel: 5,
        },
        {
            name: 'Weapon 40 R',
            dmg: 40,
            price: 660,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.weapon,
            magic: ItemMagicType.rare,
            baseLevel: 10,
        },
        {
            name: 'Shield 10% R',
            blockChance: 10,
            price: 700,
            baseValueStep: 1,
            baseValueMax: 15,
            type: InventoryType.shield,
            magic: ItemMagicType.rare,
            baseLevel: 5,
        },
        // баф холодем 100
        {
            name: 'Armor 30% R',
            blockPercent: 30,
            price: 2200,
            baseValueStep: 1,
            baseValueMax: 40,
            type: InventoryType.armor,
            magic: ItemMagicType.rare,
            baseLevel: 6,
        },
        {
            name: 'Weapon 50 R',
            dmg: 50,
            price: 1200,
            baseValueStep: 1,
            baseValueMax: 60,
            type: InventoryType.weapon,
            magic: ItemMagicType.rare,
            baseLevel: 11,
        },
        {
            name: 'Gloves 50% M',
            hitChance: 50,
            price: 10000,
            baseValueStep: 1,
            baseValueMax: 70,
            type: InventoryType.gloves,
            magic: ItemMagicType.magic,
            baseLevel: 4,
        },
        // баф водою 100
        {
            name: 'Weapon 60 M',
            dmg: 60,
            price: 1700,
            baseValueStep: 2,
            baseValueMax: 80,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 12,
        },
        {
            name: 'Shield 15% R',
            blockChance: 15,
            price: 2200,
            baseValueStep: 1,
            baseValueMax: 20,
            type: InventoryType.shield,
            magic: ItemMagicType.rare,
            baseLevel: 6,
        },
        {
            name: 'Boots 3 M',
            rate: 3,
            price: 10000,
            baseValueStep: 0.1,
            baseValueMax: 5,
            type: InventoryType.boots,
            magic: ItemMagicType.magic,
            baseLevel: 4,
        },
        {
            name: 'Weapon 60 R',
            dmg: 60,
            price: 2400,
            baseValueStep: 2,
            baseValueMax: 80,
            type: InventoryType.weapon,
            magic: ItemMagicType.rare,
            baseLevel: 12,
        },
        {
            name: 'Armor 40% M',
            blockPercent: 40,
            price: 5000,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.armor,
            magic: ItemMagicType.magic,
            baseLevel: 7,
        },
        {
            name: 'Small health potion (+150 HP)',
            hp: 150,
            price: 150,
            type: PocketItemType.healthPotion,
        },
        {
            name: 'Weapon 80',
            dmg: 80,
            price: 2000,
            baseValueStep: 2,
            baseValueMax: 100,
            type: InventoryType.weapon,
            baseLevel: 13,
        },
        {
            name: 'Helmet 5 R',
            blockValue: 5,
            price: 2000,
            baseValueStep: 1,
            baseValueMax: 10,
            type: InventoryType.helmet,
            magic: ItemMagicType.rare,
            baseLevel: 3,
        },
        {
            name: 'Weapon 80 M',
            dmg: 80,
            price: 3300,
            baseValueStep: 2,
            baseValueMax: 100,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 13,
        },
        {
            name: 'Shield 20% M',
            blockChance: 20,
            price: 5000,
            baseValueStep: 1,
            baseValueMax: 30,
            type: InventoryType.shield,
            magic: ItemMagicType.magic,
            baseLevel: 7,
        },
        {
            name: 'Gloves 70%',
            hitChance: 70,
            price: 50000,
            baseValueStep: 1,
            baseValueMax: 90,
            type: InventoryType.gloves,
            baseLevel: 5,
        },
        // руна2
        {
            name: 'Armor 50%',
            blockPercent: 50,
            price: 8000,
            baseValueStep: 1,
            baseValueMax: 60,
            type: InventoryType.armor,
            baseLevel: 8,
        },
        {
            name: 'Weapon 100',
            dmg: 100,
            price: 4000,
            baseValueStep: 1,
            baseValueMax: 120,
            type: InventoryType.weapon,
            baseLevel: 14,
        },
        {
            name: 'Boots 5',
            rate: 5,
            price: 50000,
            baseValueStep: 0.1,
            baseValueMax: 8,
            type: InventoryType.boots,
            baseLevel: 5,
        },
        {
            name: 'Shield 30%',
            blockChance: 30,
            price: 8000,
            baseValueStep: 1,
            baseValueMax: 40,
            type: InventoryType.shield,
            baseLevel: 8,
        },
        {
            name: 'Helmet 10 M',
            blockValue: 10,
            price: 10000,
            baseValueStep: 1,
            baseValueMax: 20,
            type: InventoryType.helmet,
            magic: ItemMagicType.magic,
            baseLevel: 4,
        },
        {
            name: 'Weapon 100 M',
            dmg: 100,
            price: 5300,
            baseValueStep: 1,
            baseValueMax: 120,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 14,
        },
        {
            name: 'Armor 60%',
            blockPercent: 60,
            price: 30000,
            baseValueStep: 1,
            baseValueMax: 70,
            type: InventoryType.armor,
            baseLevel: 9,
        },
        {
            name: 'Weapon 120',
            dmg: 120,
            price: 6000,
            baseValueStep: 2,
            baseValueMax: 160,
            type: InventoryType.weapon,
            baseLevel: 15,
        },
        {
            name: 'Shield 40%',
            blockChance: 40,
            price: 30000,
            baseValueStep: 1,
            baseValueMax: 60,
            type: InventoryType.shield,
            baseLevel: 9,
        },
        {
            name: 'Weapon 160',
            dmg: 160,
            price: 10000,
            baseValueStep: 2,
            baseValueMax: 200,
            type: InventoryType.weapon,
            baseLevel: 16,
        },
        {
            name: 'Helmet 20',
            blockValue: 20,
            price: 50000,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.helmet,
            baseLevel: 5,
        },
    ],
    5: [
        // сундук
        {
            name: 'Gloves 50% R',
            hitChance: 50,
            price: 20000,
            baseValueStep: 1,
            baseValueMax: 70,
            type: InventoryType.gloves,
            magic: ItemMagicType.rare,
            baseLevel: 4,
        },
        {
            name: 'Weapon 80 R',
            dmg: 80,
            price: 4600,
            baseValueStep: 2,
            baseValueMax: 100,
            type: InventoryType.weapon,
            magic: ItemMagicType.rare,
            baseLevel: 13,
        },
        {
            name: 'Boots 3 R',
            rate: 3,
            price: 20000,
            baseValueStep: 0.1,
            baseValueMax: 5,
            type: InventoryType.boots,
            magic: ItemMagicType.rare,
            baseLevel: 4,
        },
        {
            name: 'Weapon 100 R',
            dmg: 100,
            price: 6600,
            baseValueStep: 1,
            baseValueMax: 120,
            type: InventoryType.weapon,
            magic: ItemMagicType.rare,
            baseLevel: 14,
        },
        {
            name: 'Armor 40% R',
            blockPercent: 40,
            price: 7000,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.armor,
            magic: ItemMagicType.rare,
            baseLevel: 7,
        },
        {
            name: 'Weapon 120 M',
            dmg: 120,
            price: 9000,
            baseValueStep: 2,
            baseValueMax: 160,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 15,
        },
        {
            name: 'Shield 20% R',
            blockChance: 20,
            price: 7000,
            baseValueStep: 1,
            baseValueMax: 30,
            type: InventoryType.shield,
            magic: ItemMagicType.rare,
            baseLevel: 7,
        },
        {
            name: 'Weapon 120 R',
            dmg: 120,
            price: 12000,
            baseValueStep: 2,
            baseValueMax: 160,
            type: InventoryType.weapon,
            magic: ItemMagicType.rare,
            baseLevel: 15,
        },
        {
            name: 'Armor 50% M',
            blockPercent: 50,
            price: 15000,
            baseValueStep: 1,
            baseValueMax: 60,
            type: InventoryType.armor,
            magic: ItemMagicType.magic,
            baseLevel: 8,
        },
        {
            name: 'Shield 30% M',
            blockChance: 30,
            price: 15000,
            baseValueStep: 1,
            baseValueMax: 40,
            type: InventoryType.shield,
            magic: ItemMagicType.magic,
            baseLevel: 8,
        },
        {
            name: 'Weapon 160 M',
            dmg: 160,
            price: 17000,
            baseValueStep: 2,
            baseValueMax: 200,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 16,
        },
        {
            name: 'Gloves 70% M',
            hitChance: 70,
            price: 100000,
            baseValueStep: 1,
            baseValueMax: 90,
            type: InventoryType.gloves,
            magic: ItemMagicType.magic,
            baseLevel: 5,
        },
        {
            name: 'Helmet 10 R',
            blockValue: 10,
            price: 20000,
            baseValueStep: 1,
            baseValueMax: 20,
            type: InventoryType.helmet,
            magic: ItemMagicType.rare,
            baseLevel: 4,
        },
        {
            name: 'Weapon 160 R',
            dmg: 160,
            price: 24000,
            baseValueStep: 2,
            baseValueMax: 200,
            type: InventoryType.weapon,
            magic: ItemMagicType.rare,
            baseLevel: 16,
        },
        {
            name: 'Boots 5 M',
            rate: 5,
            price: 100000,
            baseValueStep: 0.1,
            baseValueMax: 8,
            type: InventoryType.boots,
            magic: ItemMagicType.magic,
            baseLevel: 5,
        },
        {
            name: 'Shield 30% R',
            blockChance: 30,
            price: 22000,
            baseValueStep: 1,
            baseValueMax: 40,
            type: InventoryType.shield,
            magic: ItemMagicType.rare,
            baseLevel: 8,
        },
        {
            name: 'Weapon 200',
            dmg: 200,
            price: 20000,
            baseValueStep: 2,
            baseValueMax: 250,
            type: InventoryType.weapon,
            baseLevel: 17,
        },
        {
            name: 'Armor 50% R',
            blockPercent: 50,
            price: 22000,
            baseValueStep: 1,
            baseValueMax: 60,
            type: InventoryType.armor,
            magic: ItemMagicType.rare,
            baseLevel: 8,
        },
        {
            name: 'Weapon 200 M',
            dmg: 200,
            price: 33000,
            baseValueStep: 2,
            baseValueMax: 250,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 17,
        },
        {
            name: 'Shield 40% M',
            blockChance: 40,
            price: 50000,
            baseValueStep: 1,
            baseValueMax: 60,
            type: InventoryType.shield,
            magic: ItemMagicType.magic,
            baseLevel: 9,
        },
        {
            name: 'Armor 60% M',
            blockPercent: 60,
            price: 50000,
            baseValueStep: 1,
            baseValueMax: 70,
            type: InventoryType.armor,
            magic: ItemMagicType.magic,
            baseLevel: 9,
        },
        {
            name: 'Weapon 200 R',
            dmg: 200,
            price: 46000,
            baseValueStep: 2,
            baseValueMax: 250,
            type: InventoryType.weapon,
            magic: ItemMagicType.rare,
            baseLevel: 17,
        },
        {
            name: 'Gloves 70% R',
            hitChance: 70,
            price: 200000,
            baseValueStep: 1,
            baseValueMax: 90,
            type: InventoryType.gloves,
            magic: ItemMagicType.rare,
            baseLevel: 5,
        },
        {
            name: 'Weapon 250',
            dmg: 250,
            price: 40000,
            baseValueStep: 2,
            baseValueMax: 300,
            type: InventoryType.weapon,
            baseLevel: 18,
        },
        {
            name: 'Boots 5 R',
            rate: 5,
            price: 200000,
            baseValueStep: 0.1,
            baseValueMax: 8,
            type: InventoryType.boots,
            magic: ItemMagicType.rare,
            baseLevel: 5,
        },
        {
            name: 'Helmet 20 M',
            blockValue: 20,
            price: 100000,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.helmet,
            magic: ItemMagicType.magic,
            baseLevel: 5,
        },
        {
            name: 'Shield 60%',
            blockChance: 60,
            price: 80000,
            baseValueStep: 1,
            baseValueMax: 80,
            type: InventoryType.shield,
            baseLevel: 10,
        },
        {
            name: 'Weapon 250 M',
            dmg: 250,
            price: 53000,
            baseValueStep: 2,
            baseValueMax: 300,
            type: InventoryType.weapon,
            magic: ItemMagicType.magic,
            baseLevel: 18,
        },
        {
            name: 'Armor 70%',
            blockPercent: 70,
            price: 80000,
            baseValueStep: 1,
            baseValueMax: 90,
            type: InventoryType.armor,
            baseLevel: 10,
        },
        {
            name: 'Helmet 20 R',
            blockValue: 20,
            price: 200000,
            baseValueStep: 1,
            baseValueMax: 50,
            type: InventoryType.helmet,
            magic: ItemMagicType.rare,
            baseLevel: 5,
        },
        {
            name: 'Weapon 300',
            dmg: 300,
            price: 60000,
            baseValueStep: 2,
            baseValueMax: 400,
            type: InventoryType.weapon,
            baseLevel: 19,
        },
        // ключ
        {
            name: 'Shield 60% M',
            blockChance: 60,
            price: 150000,
            baseValueStep: 1,
            baseValueMax: 80,
            type: InventoryType.shield,
            magic: ItemMagicType.magic,
            baseLevel: 10,
        },
        {
            name: 'Armor 70% M',
            blockPercent: 70,
            price: 150000,
            baseValueStep: 1,
            baseValueMax: 90,
            type: InventoryType.armor,
            magic: ItemMagicType.magic,
            baseLevel: 10,
        },
        {
            name: 'Weapon 400',
            dmg: 400,
            price: 100000,
            baseValueStep: 2,
            baseValueMax: 500,
            type: InventoryType.weapon,
            baseLevel: 20,
        },
    ],
};